### ISSUE TITLE
Documents uploaded with Mime Type = application/octet-stream always

### ISSUE THREAD

**Issue by denikqwerty** [BeverCRM/PCF-DragAndDropArea#28] opened 2023-09-07 10:04 UTC
When using your extension we realized that when we upload a file via Drag and Drop area it is actually uploaded with mimetype = application/octet-stream while if we upload the file via normal attachment, it is uplaoded with actual file mime type, like application/pdf, image/jpeg etc.

Can you please fix that? It is critical for us

**Comment by RubenAghajanyan** [comment] 2023-09-11 14:26
@denikqwerty 

But, files are uploading with their mime-type.  You can upload a file via control, download it from notes, and check its mime-type. https://www.htmlstrip.com/mime-file-type-checker 
It will show the correct mime-type.

Can you please share more info, how did you find out that mime-type sets application/octet-stream?

**Comment by denikqwerty** [comment] 2023-09-12 07:27
@RubenAghajanyan 

We`ve uploaded one and the same pdf to the records where we have Drag and Drop Area enabled, and as you can see mime types of them are different.

1st row represented note attached via Drag and Drop area
2nd row represents note attached via OOB process

![image](https://github.com/BeverCRM/PCF-DragAndDropArea/assets/18682294/b71af0b9-4a82-4755-9487-d0ec41f493ac)

Please tell me if you need more information. You need to check mime type not of downloaded file, but the annotation record itself, like:
<fetch>
  <entity name="annotation">
    <attribute name="objectid" />
    <attribute name="filename" />
    <attribute name="mimetype" />
    <filter>
      <condition attribute="isdocument" operator="eq" value="1" />
      <condition attribute="objectid" operator="eq" value="[id of your record]" />
    </filter>
  </entity>
</fetch>

**Comment by RubenAghajanyan** [comment] 2023-09-12 12:28
@denikqwerty,

Okey. We published a new version "1.0.2" where that bug should be fixed. Please download it from the marketplace 
https://marketplace.bevercrm.com/pcf-controls/1

**Comment by denikqwerty** [comment] 2023-09-12 12:35
@RubenAghajanyan Thank you very much for the quick fix. The issue is resoved :)

**Comment by RubenAghajanyan** [comment] 2023-09-12 12:48
The issue is resolved.

**Closed by RubenAghajanyan** 2023-09-12 12:48 UTC
